### ISSUE TITLE
发短信接口异常，能发，发完就会接口异常，作者能修复一下嘛

### ISSUE THREAD

**Issue by ngol233** [lkiuyu/smsmanager#6]
大佬能修复一下嘛，不知道怎么解决了。。
[img]https://s1.yesimg.com/2023/03/13/33368c8f0cbf1.png[/img]

**Comment by ngol233** [comment]
[img] https://s1.yesimg.com/2023/03/13/33368c8f0cbf1.png [/img]

**Comment by lkiuyu** [comment]
试试最新的dbus版本，应该不会有问题了
