### ISSUE TITLE
[wishlist]大佬能否加入tg机器人支持？

### ISSUE THREAD

**Issue by ysuolmai** [lkiuyu/smsmanager#8]
企业微信有门槛，邮箱有时候又不是特别方便，能否加一个tg机器人转发的支持？tg的消息发送极其简单

https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={chat_id}&text={message}

大概这种格式一个get就能发送。

**Comment by lkiuyu** [comment]
这个项目看等有空就更新一下，不方便的话可以试试我的另一个短信转发项目，那个项目支持转发到pushplus，就是不像这个项目有web界面管理，是个控制台项目，但同样支持短信的转发和发送

**Comment by lkiuyu** [comment]
已添加支持
